USE DW_MARIO_KART;

INSERT INTO FATO_RESULTADO(ID_RESULTADO, ID_CORRIDA, ID_PILOTO, ID_CONSTRUTOR, POS_LARGADA, POS_FINAL, PONTOS_CORRIDA, RANK_VOLTA_RAPIDA, PONTO_VOLTA_RAPIDA, STATUS)
SELECT resultado.ID_RESULTADO, resultado.ID_CORRIDA, resultado.ID_PILOTO, resultado.ID_CONSTRUTOR, resultado.POS_LARGADA, resultado.POS_FINAL, resultado.PONTOS_CORRIDA, resultado.RANK_VOLTA_RAPIDA, resultado.PONTO_VOLTA_RAPIDA, status.DESCRICAO
FROM db_mario_kart.tb_resultado resultado
	JOIN db_mario_kart.tb_status status ON resultado.ID_STATUS = status.ID_STATUS;