USE DB_MARIO_KART;

insert into TB_PAIS(NOME_PAIS) values('Afghanistan');
insert into TB_PAIS(NOME_PAIS) values('Albania');
insert into TB_PAIS(NOME_PAIS) values('Algeria');
insert into TB_PAIS(NOME_PAIS) values('Andorra');
insert into TB_PAIS(NOME_PAIS) values('Angola');
insert into TB_PAIS(NOME_PAIS) values('Antigua and Barbuda');
insert into TB_PAIS(NOME_PAIS) values('Argentina');
insert into TB_PAIS(NOME_PAIS) values('Armenia');
insert into TB_PAIS(NOME_PAIS) values('Australia');
insert into TB_PAIS(NOME_PAIS) values('Austria');
insert into TB_PAIS(NOME_PAIS) values('Azerbaijan');
insert into TB_PAIS(NOME_PAIS) values('The Bahamas');
insert into TB_PAIS(NOME_PAIS) values('Bahrain');
insert into TB_PAIS(NOME_PAIS) values('Bangladesh');
insert into TB_PAIS(NOME_PAIS) values('Barbados');
insert into TB_PAIS(NOME_PAIS) values('Belarus');
insert into TB_PAIS(NOME_PAIS) values('Belgium');
insert into TB_PAIS(NOME_PAIS) values('Belize');
insert into TB_PAIS(NOME_PAIS) values('Benin');
insert into TB_PAIS(NOME_PAIS) values('Bhutan');
insert into TB_PAIS(NOME_PAIS) values('Bolivia');
insert into TB_PAIS(NOME_PAIS) values('Bosnia and Herzegovina');
insert into TB_PAIS(NOME_PAIS) values('Botswana');
insert into TB_PAIS(NOME_PAIS) values('Brazil');
insert into TB_PAIS(NOME_PAIS) values('Brunei');
insert into TB_PAIS(NOME_PAIS) values('Bulgaria');
insert into TB_PAIS(NOME_PAIS) values('Burkina Faso');
insert into TB_PAIS(NOME_PAIS) values('Burundi');
insert into TB_PAIS(NOME_PAIS) values('Cabo Verde');
insert into TB_PAIS(NOME_PAIS) values('Cambodia');
insert into TB_PAIS(NOME_PAIS) values('Cameroon');
insert into TB_PAIS(NOME_PAIS) values('Canada');
insert into TB_PAIS(NOME_PAIS) values('Central African Republic');
insert into TB_PAIS(NOME_PAIS) values('Chad');
insert into TB_PAIS(NOME_PAIS) values('Chile');
insert into TB_PAIS(NOME_PAIS) values('China');
insert into TB_PAIS(NOME_PAIS) values('Colombia');
insert into TB_PAIS(NOME_PAIS) values('Comoros');
insert into TB_PAIS(NOME_PAIS) values('Democratic Republic of the Congo');
insert into TB_PAIS(NOME_PAIS) values('Republic of the Congo');
insert into TB_PAIS(NOME_PAIS) values('Costa Rica');
insert into TB_PAIS(NOME_PAIS) values('Côte d’Ivoire');
insert into TB_PAIS(NOME_PAIS) values('Croatia');
insert into TB_PAIS(NOME_PAIS) values('Cuba');
insert into TB_PAIS(NOME_PAIS) values('Cyprus');
insert into TB_PAIS(NOME_PAIS) values('Czech Republic');
insert into TB_PAIS(NOME_PAIS) values('Denmark');
insert into TB_PAIS(NOME_PAIS) values('Djibouti');
insert into TB_PAIS(NOME_PAIS) values('Dominica');
insert into TB_PAIS(NOME_PAIS) values('Dominican Republic');
insert into TB_PAIS(NOME_PAIS) values('East Timor (Timor-Leste)');
insert into TB_PAIS(NOME_PAIS) values('Ecuador');
insert into TB_PAIS(NOME_PAIS) values('Egypt');
insert into TB_PAIS(NOME_PAIS) values('El Salvador');
insert into TB_PAIS(NOME_PAIS) values('Equatorial Guinea');
insert into TB_PAIS(NOME_PAIS) values('Eritrea');
insert into TB_PAIS(NOME_PAIS) values('Estonia');
insert into TB_PAIS(NOME_PAIS) values('Eswatini');
insert into TB_PAIS(NOME_PAIS) values('Ethiopia');
insert into TB_PAIS(NOME_PAIS) values('Fiji');
insert into TB_PAIS(NOME_PAIS) values('Finland');
insert into TB_PAIS(NOME_PAIS) values('France');
insert into TB_PAIS(NOME_PAIS) values('Gabon');
insert into TB_PAIS(NOME_PAIS) values('The Gambia');
insert into TB_PAIS(NOME_PAIS) values('Georgia');
insert into TB_PAIS(NOME_PAIS) values('Germany');
insert into TB_PAIS(NOME_PAIS) values('Ghana');
insert into TB_PAIS(NOME_PAIS) values('Greece');
insert into TB_PAIS(NOME_PAIS) values('Grenada');
insert into TB_PAIS(NOME_PAIS) values('Guatemala');
insert into TB_PAIS(NOME_PAIS) values('Guinea');
insert into TB_PAIS(NOME_PAIS) values('Guinea-Bissau');
insert into TB_PAIS(NOME_PAIS) values('Guyana');
insert into TB_PAIS(NOME_PAIS) values('Haiti');
insert into TB_PAIS(NOME_PAIS) values('Honduras');
insert into TB_PAIS(NOME_PAIS) values('Hungary');
insert into TB_PAIS(NOME_PAIS) values('Iceland');
insert into TB_PAIS(NOME_PAIS) values('India');
insert into TB_PAIS(NOME_PAIS) values('Indonesia');
insert into TB_PAIS(NOME_PAIS) values('Iran');
insert into TB_PAIS(NOME_PAIS) values('Iraq');
insert into TB_PAIS(NOME_PAIS) values('Ireland');
insert into TB_PAIS(NOME_PAIS) values('Israel');
insert into TB_PAIS(NOME_PAIS) values('Italy');
insert into TB_PAIS(NOME_PAIS) values('Jamaica');
insert into TB_PAIS(NOME_PAIS) values('Japan');
insert into TB_PAIS(NOME_PAIS) values('Jordan');
insert into TB_PAIS(NOME_PAIS) values('Kazakhstan');
insert into TB_PAIS(NOME_PAIS) values('Kenya');
insert into TB_PAIS(NOME_PAIS) values('Kiribati');
insert into TB_PAIS(NOME_PAIS) values('North Korea');
insert into TB_PAIS(NOME_PAIS) values('South Korea');
insert into TB_PAIS(NOME_PAIS) values('Kosovo');
insert into TB_PAIS(NOME_PAIS) values('Kuwait');
insert into TB_PAIS(NOME_PAIS) values('Kyrgyzstan');
insert into TB_PAIS(NOME_PAIS) values('Laos');
insert into TB_PAIS(NOME_PAIS) values('Latvia');
insert into TB_PAIS(NOME_PAIS) values('Lebanon');
insert into TB_PAIS(NOME_PAIS) values('Lesotho');
insert into TB_PAIS(NOME_PAIS) values('Liberia');
insert into TB_PAIS(NOME_PAIS) values('Libya');
insert into TB_PAIS(NOME_PAIS) values('Liechtenstein');
insert into TB_PAIS(NOME_PAIS) values('Lithuania');
insert into TB_PAIS(NOME_PAIS) values('Luxembourg');
insert into TB_PAIS(NOME_PAIS) values('Madagascar');
insert into TB_PAIS(NOME_PAIS) values('Malawi');
insert into TB_PAIS(NOME_PAIS) values('Malaysia');
insert into TB_PAIS(NOME_PAIS) values('Maldives');
insert into TB_PAIS(NOME_PAIS) values('Mali');
insert into TB_PAIS(NOME_PAIS) values('Malta');
insert into TB_PAIS(NOME_PAIS) values('Marshall Islands');
insert into TB_PAIS(NOME_PAIS) values('Mauritania');
insert into TB_PAIS(NOME_PAIS) values('Mauritius');
insert into TB_PAIS(NOME_PAIS) values('Mexico');
insert into TB_PAIS(NOME_PAIS) values('Micronesia');
insert into TB_PAIS(NOME_PAIS) values('Moldova');
insert into TB_PAIS(NOME_PAIS) values('Monaco');
insert into TB_PAIS(NOME_PAIS) values('Mongolia');
insert into TB_PAIS(NOME_PAIS) values('Montenegro');
insert into TB_PAIS(NOME_PAIS) values('Morocco');
insert into TB_PAIS(NOME_PAIS) values('Mozambique');
insert into TB_PAIS(NOME_PAIS) values('Myanmar (Burma)');
insert into TB_PAIS(NOME_PAIS) values('Namibia');
insert into TB_PAIS(NOME_PAIS) values('Nauru');
insert into TB_PAIS(NOME_PAIS) values('Nepal');
insert into TB_PAIS(NOME_PAIS) values('Netherlands');
insert into TB_PAIS(NOME_PAIS) values('New Zealand');
insert into TB_PAIS(NOME_PAIS) values('Nicaragua');
insert into TB_PAIS(NOME_PAIS) values('Niger');
insert into TB_PAIS(NOME_PAIS) values('Nigeria');
insert into TB_PAIS(NOME_PAIS) values('North Macedonia');
insert into TB_PAIS(NOME_PAIS) values('Norway');
insert into TB_PAIS(NOME_PAIS) values('Oman');
insert into TB_PAIS(NOME_PAIS) values('Pakistan');
insert into TB_PAIS(NOME_PAIS) values('Palau');
insert into TB_PAIS(NOME_PAIS) values('Panama');
insert into TB_PAIS(NOME_PAIS) values('Papua New Guinea');
insert into TB_PAIS(NOME_PAIS) values('Paraguay');
insert into TB_PAIS(NOME_PAIS) values('Peru');
insert into TB_PAIS(NOME_PAIS) values('Philippines');
insert into TB_PAIS(NOME_PAIS) values('Poland');
insert into TB_PAIS(NOME_PAIS) values('Portugal');
insert into TB_PAIS(NOME_PAIS) values('Qatar');
insert into TB_PAIS(NOME_PAIS) values('Romania');
insert into TB_PAIS(NOME_PAIS) values('Russia');
insert into TB_PAIS(NOME_PAIS) values('Rwanda');
insert into TB_PAIS(NOME_PAIS) values('Saint Kitts and Nevis');
insert into TB_PAIS(NOME_PAIS) values('Saint Lucia');
insert into TB_PAIS(NOME_PAIS) values('Saint Vincent and the Grenadines');
insert into TB_PAIS(NOME_PAIS) values('Samoa');
insert into TB_PAIS(NOME_PAIS) values('San Marino');
insert into TB_PAIS(NOME_PAIS) values('Sao Tome and Principe');
insert into TB_PAIS(NOME_PAIS) values('Saudi Arabia');
insert into TB_PAIS(NOME_PAIS) values('Senegal');
insert into TB_PAIS(NOME_PAIS) values('Serbia');
insert into TB_PAIS(NOME_PAIS) values('Seychelles');
insert into TB_PAIS(NOME_PAIS) values('Sierra Leone');
insert into TB_PAIS(NOME_PAIS) values('Singapore');
insert into TB_PAIS(NOME_PAIS) values('Slovakia');
insert into TB_PAIS(NOME_PAIS) values('Slovenia');
insert into TB_PAIS(NOME_PAIS) values('Solomon Islands');
insert into TB_PAIS(NOME_PAIS) values('Somalia');
insert into TB_PAIS(NOME_PAIS) values('South Africa');
insert into TB_PAIS(NOME_PAIS) values('Spain');
insert into TB_PAIS(NOME_PAIS) values('Sri Lanka');
insert into TB_PAIS(NOME_PAIS) values('Sudan');
insert into TB_PAIS(NOME_PAIS) values('South Sudan');
insert into TB_PAIS(NOME_PAIS) values('Suriname');
insert into TB_PAIS(NOME_PAIS) values('Sweden');
insert into TB_PAIS(NOME_PAIS) values('Switzerland');
insert into TB_PAIS(NOME_PAIS) values('Syria');
insert into TB_PAIS(NOME_PAIS) values('Taiwan');
insert into TB_PAIS(NOME_PAIS) values('Tajikistan');
insert into TB_PAIS(NOME_PAIS) values('Tanzania');
insert into TB_PAIS(NOME_PAIS) values('Thailand');
insert into TB_PAIS(NOME_PAIS) values('Togo');
insert into TB_PAIS(NOME_PAIS) values('Tonga');
insert into TB_PAIS(NOME_PAIS) values('Trinidad and Tobago');
insert into TB_PAIS(NOME_PAIS) values('Tunisia');
insert into TB_PAIS(NOME_PAIS) values('Turkey');
insert into TB_PAIS(NOME_PAIS) values('Turkmenistan');
insert into TB_PAIS(NOME_PAIS) values('Tuvalu');
insert into TB_PAIS(NOME_PAIS) values('Uganda');
insert into TB_PAIS(NOME_PAIS) values('Ukraine');
insert into TB_PAIS(NOME_PAIS) values('United Arab Emirates');
insert into TB_PAIS(NOME_PAIS) values('United Kingdom');
insert into TB_PAIS(NOME_PAIS) values('United States');
insert into TB_PAIS(NOME_PAIS) values('Uruguay');
insert into TB_PAIS(NOME_PAIS) values('Uzbekistan');
insert into TB_PAIS(NOME_PAIS) values('Vanuatu');
insert into TB_PAIS(NOME_PAIS) values('Vatican City');
insert into TB_PAIS(NOME_PAIS) values('Venezuela');
insert into TB_PAIS(NOME_PAIS) values('Vietnam');
insert into TB_PAIS(NOME_PAIS) values('Yemen');
insert into TB_PAIS(NOME_PAIS) values('Zambia');
insert into TB_PAIS(NOME_PAIS) values('Zimbabwe');