USE DB_MARIO_KART;

insert into TB_STATUS(ID_STATUS, DESCRICAO) values(1,"Finished");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(2,"Disqualified");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(3,"Accident");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(4,"Collision");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(5,"Engine");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(6,"Gearbox");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(7,"Transmission");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(8,"Clutch");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(9,"Hydraulics");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(10,"Electrical");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(11,"+1 Lap");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(12,"+2 Laps");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(13,"+3 Laps");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(14,"+4 Laps");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(15,"+5 Laps");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(16,"+6 Laps");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(17,"+7 Laps");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(18,"+8 Laps");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(19,"+9 Laps");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(20,"Spun off");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(21,"Radiator");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(22,"Suspension");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(23,"Brakes");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(24,"Differential");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(25,"Overheating");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(26,"Mechanical");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(27,"Tyre");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(28,"Driver Seat");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(29,"Puncture");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(30,"Driveshaft");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(31,"Retired");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(32,"Fuel pressure");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(33,"Front wing");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(34,"Water pressure");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(35,"Refuelling");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(36,"Wheel");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(37,"Throttle");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(38,"Steering");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(39,"Technical");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(40,"Electronics");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(41,"Broken wing");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(42,"Heat shield fire");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(43,"Exhaust");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(44,"Oil leak");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(45,"+11 Laps");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(46,"Wheel rim");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(47,"Water leak");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(48,"Fuel pump");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(49,"Track rod");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(50,"+17 Laps");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(51,"Oil pressure");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(128,"+42 Laps");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(53,"+13 Laps");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(54,"Withdrew");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(55,"+12 Laps");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(56,"Engine fire");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(129,"Engine misfire");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(58,"+26 Laps");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(59,"Tyre puncture");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(60,"Out of fuel");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(61,"Wheel nut");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(62,"Not classified");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(63,"Pneumatics");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(64,"Handling");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(65,"Rear wing");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(66,"Fire");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(67,"Wheel bearing");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(68,"Physical");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(69,"Fuel system");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(70,"Oil line");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(71,"Fuel rig");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(72,"Launch control");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(73,"Injured");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(74,"Fuel");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(75,"Power loss");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(76,"Vibrations");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(77,"107% Rule");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(78,"Safety");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(79,"Drivetrain");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(80,"Ignition");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(81,"Did not qualify");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(82,"Injury");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(83,"Chassis");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(84,"Battery");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(85,"Stalled");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(86,"Halfshaft");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(87,"Crankshaft");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(88,"+10 Laps");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(89,"Safety concerns");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(90,"Not restarted");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(91,"Alternator");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(92,"Underweight");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(93,"Safety belt");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(94,"Oil pump");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(95,"Fuel leak");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(96,"Excluded");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(97,"Did not prequalify");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(98,"Injection");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(99,"Distributor");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(100,"Driver unwell");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(101,"Turbo");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(102,"CV joint");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(103,"Water pump");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(104,"Fatal accident");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(105,"Spark plugs");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(106,"Fuel pipe");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(107,"Eye injury");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(108,"Oil pipe");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(109,"Axle");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(110,"Water pipe");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(111,"+14 Laps");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(112,"+15 Laps");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(113,"+25 Laps");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(114,"+18 Laps");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(115,"+22 Laps");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(116,"+16 Laps");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(117,"+24 Laps");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(118,"+29 Laps");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(119,"+23 Laps");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(120,"+21 Laps");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(121,"Magneto");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(122,"+44 Laps");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(123,"+30 Laps");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(124,"+19 Laps");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(125,"+46 Laps");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(126,"Supercharger");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(127,"+20 Laps");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(130,"Collision damage");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(131,"Power Unit");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(132,"ERS");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(133,"+49 Laps");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(134,"+38 Laps");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(135,"Brake duct");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(136,"Seat");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(137,"Damage");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(138,"Debris");
insert into TB_STATUS(ID_STATUS, DESCRICAO) values(139,"Illness");